---
AWSTemplateFormatVersion: '2010-09-09'
Description: A template for deploying the RSA key rotation to be used by the AWS Secrets Manager
Parameters:
  LambdaSourceBucket:
    Type: String
  LambdaSourceKey:
    Type: String
Resources:

  LambdaCustomCFNPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue SecretsManager-RSAKeyRotationLambdaARN
      Action: 'lambda:InvokeFunction'
      Principal: !ImportValue cfn-secret-provider-RoleARN

  # Custom CFN Type - secrets manager secret
  SecretsManagerSecret:
    Type: Custom::SecretsManagerSecret
    Properties:
      Name: !Sub '${AWS::StackName}-demo-secret-test-10'
      LambdaARN: !ImportValue SecretsManager-RSAKeyRotationLambdaARN
      Interval: 1
      ServiceToken: !ImportValue cfn-secret-provider-ARN
